version: '3.8'

services:
    app:
        build:
            context: ./docker/php
        volumes:
            - ./pets:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:1.25-alpine
        ports:
            - "8083:80"
        volumes:
            - ./pets:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
